In [1]:
import pandas as pd

In [2]:
result_df = []
# 打开文件
with open('evaluation.log', 'r') as f:
    # 逐行读取文件内容
    for line in f:
        # 去除行尾的换行符并打印每一行
        infos = line.replace(' ', '').replace('(', '').replace(')', '').strip().split('{')
        li = infos[0].split("'")
        # time = li[0]
        dataset_name = li[1]
        model_name = li[3]
        batch_size, weight_decay, learning_rate = [l for l in li[4].split(',') if l]
        tmp = infos[1].split('}')
        epoch2loss = tmp[0]
        best_epoch, best_loss, fix_noiselevel, init_noiselevel, dropout_prob = [s for s in tmp[1].split(',') if s]
        result_df.append((dataset_name, model_name, batch_size, weight_decay, learning_rate, epoch2loss, best_epoch, best_loss, fix_noiselevel, init_noiselevel, dropout_prob))

In [3]:
result_df = pd.DataFrame(result_df, columns=['dataset_name', 'model_name', 'batch_size', 'weight_decay', 'learning_rate', 'epoch2loss', 'best_epoch', 'best_loss', 'fix_noiselevel', 'init_noiselevel', 'dropout_prob'])

In [4]:
result_df['batch_size'] = result_df['batch_size'].astype(int)
result_df['weight_decay'] = result_df['weight_decay'].astype(float)
result_df['learning_rate'] = result_df['learning_rate'].astype(float)
result_df['best_epoch'] = result_df['best_epoch'].astype(int)
result_df['best_loss'] = result_df['best_loss'].astype(float)
result_df['fix_noiselevel'] = result_df['fix_noiselevel'].astype(float)
result_df['init_noiselevel'] = result_df['init_noiselevel'].astype(float)
result_df['dropout_prob'] = result_df['dropout_prob'].astype(float)

In [5]:
FCN_result_df = result_df[result_df['model_name']=='FCN']
noisyFCN_result_df = result_df[result_df['model_name']=='noisyFCN']
fixnoiseFCN_result_df = result_df[result_df['model_name']=='fixnoiseFCN']
dropoutFCN_result_df = result_df[result_df['model_name']=='FCN']

In [6]:
noisyFCN_result_df = noisyFCN_result_df.loc[noisyFCN_result_df.groupby(['dataset_name', 'batch_size', 'weight_decay', 'learning_rate'])['best_loss'].idxmin().reset_index(drop=True)]
fixnoiseFCN_result_df = fixnoiseFCN_result_df.loc[fixnoiseFCN_result_df.groupby(['dataset_name', 'batch_size', 'weight_decay', 'learning_rate'])['best_loss'].idxmin().reset_index(drop=True)]
dropoutFCN_result_df = dropoutFCN_result_df.loc[dropoutFCN_result_df.groupby(['dataset_name', 'batch_size', 'weight_decay', 'learning_rate'])['best_loss'].idxmin().reset_index(drop=True)]

In [7]:
df1 = pd.merge(FCN_result_df, noisyFCN_result_df, on=['dataset_name', 'batch_size', 'weight_decay', 'learning_rate'], how='inner', suffixes=('_FCN', '_noisyFCN'))
df2 = pd.merge(df1, fixnoiseFCN_result_df, on=['dataset_name', 'batch_size', 'weight_decay', 'learning_rate'], how='inner')
df3 = pd.merge(df2, dropoutFCN_result_df, on=['dataset_name', 'batch_size', 'weight_decay', 'learning_rate'], how='inner', suffixes=('_fixnoiseFCN', '_dropoutFCN'))
df3

,dataset_name,model_name_FCN,batch_size,weight_decay,learning_rate,epoch2loss_FCN,best_epoch_FCN,best_loss_FCN,fix_noiselevel_FCN,init_noiselevel_FCN,...,fix_noiselevel_fixnoiseFCN,init_noiselevel_fixnoiseFCN,dropout_prob_fixnoiseFCN,model_name_dropoutFCN,epoch2loss_dropoutFCN,best_epoch_dropoutFCN,best_loss_dropoutFCN,fix_noiselevel_dropoutFCN,init_noiselevel_dropoutFCN,dropout_prob_dropoutFCN
0,bostonHousing,FCN,32,0.10000,0.0010,"0:0.6341015617420644,10:0.23431518995835457,20...",130,0.207891,0.01,0.01,...,0.010,0.01,0.01,FCN,"0:0.6341015617420644,10:0.23431518995835457,20...",130,0.207891,0.01,0.01,0.01
1,bostonHousing,FCN,32,0.01000,0.0010,"0:0.5677161419097289,10:0.1969293736749225,20:...",100,0.164547,0.01,0.01,...,0.100,0.01,0.01,FCN,"0:0.6014782229691377,10:0.1981834783230299,20:...",120,0.159199,0.01,0.01,0.01
2,energy,FCN,32,0.10000,0.0010,"0:0.30231431666118663,10:0.0870186047472867,20...",20,0.086956,0.01,0.01,...,0.010,0.01,0.01,FCN,"0:0.30231431666118663,10:0.0870186047472867,20...",20,0.086956,0.01,0.01,0.01
3,bostonHousing,FCN,32,0.00100,0.0010,"0:0.5252858572168114,10:0.1819583551751243,20:...",80,0.150847,0.01,0.01,...,0.010,0.01,0.01,FCN,"0:0.5782190397933678,10:0.18263521562387913,20...",90,0.144284,0.01,0.01,0.01
4,bostonHousing,FCN,32,0.00010,0.0010,"0:0.5802548202099623,10:0.1909585953126719,20:...",90,0.143937,0.01,0.01,...,0.100,0.01,0.01,FCN,"0:0.5802548202099623,10:0.1909585953126719,20:...",90,0.143937,0.01,0.01,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,yacht,FCN,32,0.00001,0.0001,"0:1.0078539351249227,10:0.757653199609445,20:0...",980,0.052215,0.01,0.01,...,0.010,0.01,0.01,FCN,"0:1.0078539351249227,10:0.757653199609445,20:0...",980,0.052215,0.01,0.01,0.01
186,yacht,FCN,32,0.00010,0.0020,"0:0.5923495749137839,10:0.07575875860513473,20...",40,0.049069,0.01,0.01,...,0.001,0.01,0.01,FCN,"0:0.5923495749137839,10:0.07575875860513473,20...",40,0.049069,0.01,0.01,0.01
187,yacht,FCN,32,0.00010,0.0010,"0:0.7705993964866715,10:0.1784539264732478,20:...",120,0.046754,0.01,0.01,...,0.050,0.01,0.01,FCN,"0:0.7705993964866715,10:0.1784539264732478,20:...",120,0.046754,0.01,0.01,0.01
188,yacht,FCN,32,0.00010,0.0005,"0:0.8739541286108444,10:0.29644687103616946,20...",320,0.046965,0.01,0.01,...,0.050,0.01,0.01,FCN,"0:0.8739541286108444,10:0.29644687103616946,20...",320,0.046965,0.01,0.01,0.01
189,yacht,FCN,32,0.00010,0.0001,"0:0.9760673938284115,10:0.7509658368412329,20:...",1150,0.050715,0.01,0.01,...,0.010,0.01,0.01,FCN,"0:0.9760673938284115,10:0.7509658368412329,20:...",1150,0.050715,0.01,0.01,0.01

In [8]:
df3.groupby('dataset_name')[['best_loss_FCN', 'best_loss_noisyFCN', 'best_loss_fixnoiseFCN', 'best_loss_dropoutFCN']].min()

,best_loss_FCN,best_loss_noisyFCN,best_loss_fixnoiseFCN,best_loss_dropoutFCN
dataset_name,,,,
bostonHousing,0.130827,0.129769,0.137724,0.130827
concrete,0.099598,0.098690,0.100055,0.099598
energy,0.010171,0.009672,0.007750,0.010171
kin8nm,0.075654,0.073846,0.071565,0.075654
power-plant,0.049791,0.049633,0.049072,0.049791
protein-tertiary-structure,0.476229,0.463667,0.445849,0.476229
wine-quality-red,0.597357,0.596099,0.591271,0.597357
yacht,0.040630,0.037691,0.039768,0.040630

In [9]:
pd.merge(FCN_result_df, noisyFCN_result_df, on=['dataset_name', 'batch_size', 'weight_decay', 'learning_rate'], how='inner').groupby('dataset_name')[['best_loss_x', 'best_loss_y']].min()

                            best_loss_x  best_loss_y
dataset_name
bostonHousing                  0.130827     0.129769
concrete                       0.099598     0.098690
energy                         0.010171     0.009672
kin8nm                         0.075654     0.073846
power-plant                    0.049791     0.049633
protein-tertiary-structure     0.476229     0.463667
wine-quality-red               0.597357     0.596099
yacht                          0.040630     0.037691

In [10]:
pd.merge(FCN_result_df, fixnoiseFCN_result_df, on=['dataset_name', 'batch_size', 'weight_decay', 'learning_rate'], how='inner').groupby('dataset_name')[['best_loss_x', 'best_loss_y']].min()

                            best_loss_x  best_loss_y
dataset_name
bostonHousing                  0.130827     0.137724
concrete                       0.099598     0.100055
energy                         0.010171     0.007750
kin8nm                         0.075654     0.071565
power-plant                    0.049791     0.049072
protein-tertiary-structure     0.476229     0.445849
wine-quality-red               0.597357     0.591271
yacht                          0.040630     0.039768

In [11]:
pd.merge(fixnoiseFCN_result_df, dropoutFCN_result_df, on=['dataset_name', 'batch_size', 'weight_decay', 'learning_rate'], how='inner').groupby('dataset_name')[['best_loss_x', 'best_loss_y']].min()

                            best_loss_x  best_loss_y
dataset_name
bostonHousing                  0.137724     0.130827
concrete                       0.100055     0.099598
energy                         0.007750     0.010171
kin8nm                         0.071565     0.075654
power-plant                    0.049072     0.049791
protein-tertiary-structure     0.445849     0.476229
wine-quality-red               0.591271     0.597357
yacht                          0.039768     0.040630

In [12]:
result_df[result_df['batch_size']==32].groupby(['dataset_name', 'model_name'])['best_loss'].min()

dataset_name                model_name
bostonHousing               FCN            0.130827
                            dropoutFCN     0.123964
                            fixnoiseFCN    0.137724
                            noisyFCN       0.129769
concrete                    FCN            0.099598
                            dropoutFCN     0.091614
                            fixnoiseFCN    0.100055
                            noisyFCN       0.098690
energy                      FCN            0.010171
                            dropoutFCN     0.009046
                            fixnoiseFCN    0.007750
                            noisyFCN       0.009672
kin8nm                      FCN            0.075654
                            dropoutFCN     0.072283
                            fixnoiseFCN    0.071565
                            noisyFCN       0.073846
power-plant                 FCN            0.049791
                            dropoutFCN     0.049262
                            fixnoiseFCN    0.049072
                            noisyFCN       0.049633
protein-tertiary-structure  FCN            0.476229
                            dropoutFCN     0.454932
                            fixnoiseFCN    0.445849
                            noisyFCN       0.463667
wine-quality-red            FCN            0.597357
                            dropoutFCN     0.589812
                            fixnoiseFCN    0.591271
                            noisyFCN       0.596099
yacht                       FCN            0.040630
                            dropoutFCN     0.037409
                            fixnoiseFCN    0.039768
                            noisyFCN       0.037691
Name: best_loss, dtype: float64

In [13]:
result_df.iloc[result_df[result_df['batch_size']==32].groupby(['dataset_name', 'model_name'])['best_loss'].idxmin().values]

,dataset_name,model_name,batch_size,weight_decay,learning_rate,epoch2loss,best_epoch,best_loss,fix_noiselevel,init_noiselevel,dropout_prob
295,bostonHousing,FCN,32,1.000000e-09,0.0020,"0:0.42754516290661726,10:0.16623258088473922,2...",50,0.130827,0.010,0.010,0.010
788,bostonHousing,dropoutFCN,32,1.000000e-05,0.0020,"0:0.4545082779762186,10:0.18016028223950187,20...",140,0.123964,0.010,0.010,0.100
889,bostonHousing,fixnoiseFCN,32,1.000000e-04,0.0020,"0:0.42114480491037726,10:0.16427625270537388,2...",50,0.137724,0.100,0.010,0.010
984,bostonHousing,noisyFCN,32,1.000000e-03,0.0020,"0:0.42697348813583824,10:0.17045451636299674,2...",110,0.129769,0.010,0.001,0.010
1625,concrete,FCN,32,1.000000e-03,0.0001,"0:0.932977069548475,10:0.47344995766063125,20:...",950,0.099598,0.010,0.010,0.010
2357,concrete,dropoutFCN,32,1.000000e-03,0.0020,"0:0.41101030909874137,10:0.1586751767206615,20...",230,0.091614,0.100,0.010,0.100
2178,concrete,fixnoiseFCN,32,1.000000e-04,0.0010,"0:0.5148124917674224,10:0.16869788727228147,20...",160,0.100055,0.100,0.010,0.010
2224,concrete,noisyFCN,32,1.000000e-03,0.0001,"0:0.9504759899598973,10:0.4741835464077885,20:...",790,0.098690,0.010,0.005,0.010
2572,energy,FCN,32,1.000000e-03,0.0001,"0:0.8502539616226594,10:0.16573131187397785,20...",1100,0.010171,0.010,0.010,0.010
2904,energy,dropoutFCN,32,1.000000e-05,0.0020,"0:0.14657467055400974,10:0.06154995248571691,2...",110,0.009046,0.100,0.010,0.010
1758,energy,fixnoiseFCN,32,1.000000e-04,0.0020,"0:0.13888516367240442,10:0.05993225730505765,2...",140,0.007750,0.050,0.010,0.010
2809,energy,noisyFCN,32,1.000000e-03,0.0010,"0:0.21069632132407207,10:0.06689823095932627,2...",180,0.009672,0.010,0.001,0.010
3031,kin8nm,FCN,32,1.000000e-03,0.0001,"0:0.6882557630484868,10:0.281062740617017,20:0...",990,0.075654,0.010,0.010,0.010
1825,kin8nm,dropoutFCN,32,1.000000e-04,0.0001,"0:0.6941019174766401,10:0.3073331258067295,20:...",420,0.072283,0.010,0.010,0.050
3380,kin8nm,fixnoiseFCN,32,1.000000e-03,0.0001,"0:0.6914584127678773,10:0.290696771158208,20:0...",410,0.071565,0.100,0.010,0.010
3613,kin8nm,noisyFCN,32,1.000000e-03,0.0001,"0:0.6952972416145836,10:0.27510637251101255,20...",770,0.073846,0.010,0.050,0.010
922,power-plant,FCN,32,1.000000e-09,0.0001,"0:0.119168637494007,10:0.05840804309454861,20:...",900,0.049791,0.010,0.010,0.010
4236,power-plant,dropoutFCN,32,1.000000e-09,0.0005,"0:0.06214165934598563,10:0.05689844091759474,2...",300,0.049262,0.100,0.100,0.005
3386,power-plant,fixnoiseFCN,32,1.000000e-09,0.0010,"0:0.062121207211916704,10:0.05771188768329921,...",250,0.049072,0.050,0.010,0.010
3717,power-plant,noisyFCN,32,1.000000e-09,0.0005,"0:0.061912036158863724,10:0.05718635360525901,...",250,0.049633,0.010,0.001,0.010
4269,protein-tertiary-structure,FCN,32,1.000000e-05,0.0001,"0:0.7046447294446507,10:0.5931290703621585,20:...",420,0.476229,0.010,0.010,0.010
2642,protein-tertiary-structure,dropoutFCN,32,1.000000e-04,0.0001,"0:0.7193829137214173,10:0.6117353486545947,20:...",430,0.454932,0.010,0.010,0.100
4605,protein-tertiary-structure,fixnoiseFCN,32,1.000000e-05,0.0005,"0:0.640899421405493,10:0.5305725805961176,20:0...",150,0.445849,0.050,0.010,0.010
4643,protein-tertiary-structure,noisyFCN,32,1.000000e-03,0.0005,"0:0.6445964563084088,10:0.5433830105470941,20:...",470,0.463667,0.010,0.050,0.010
4372,wine-quality-red,FCN,32,1.000000e-04,0.0001,"0:0.9275155303671079,10:0.6370654262339368,20:...",90,0.597357,0.010,0.010,0.010
589,wine-quality-red,dropoutFCN,32,1.000000e-02,0.0010,"0:0.6812982648757158,10:0.6071111657748036,20:...",210,0.589812,0.010,0.010,0.200
1324,wine-quality-red,fixnoiseFCN,32,1.000000e-03,0.0001,"0:0.9512627802584686,10:0.6356364690176413,20:...",90,0.591271,0.010,0.010,0.010
4453,wine-quality-red,noisyFCN,32,1.000000e-03,0.0005,"0:0.7440498685661485,10:0.5960992919931225,20:...",10,0.596099,0.010,0.001,0.010
4526,yacht,FCN,32,1.000000e-03,0.0010,"0:0.7471171813400425,10:0.15211861834112478,20...",150,0.040630,0.010,0.010,0.010
1027,yacht,dropoutFCN,32,1.000000e-03,0.0020,"0:0.5736339195504481,10:0.077959769819464,20:0...",90,0.037409,0.010,0.010,0.001
1883,yacht,fixnoiseFCN,32,1.000000e-03,0.0020,"0:0.5445153559105738,10:0.07399433667927371,20...",170,0.039768,0.005,0.010,0.010
4451,yacht,noisyFCN,32,1.000000e-05,0.0010,"0:0.7474827848064656,10:0.15739880489938113,20...",160,0.037691,0.010,0.050,0.010

In [14]:
result_df.iloc[result_df[(result_df['batch_size']==32) & (result_df['model_name']=='noisyFCN')].groupby(['dataset_name', 'model_name'])['best_loss'].idxmin().values]

,dataset_name,model_name,batch_size,weight_decay,learning_rate,epoch2loss,best_epoch,best_loss,fix_noiselevel,init_noiselevel,dropout_prob
984,bostonHousing,noisyFCN,32,1.000000e-03,0.0020,"0:0.42697348813583824,10:0.17045451636299674,2...",110,0.129769,0.01,0.001,0.01
2224,concrete,noisyFCN,32,1.000000e-03,0.0001,"0:0.9504759899598973,10:0.4741835464077885,20:...",790,0.098690,0.01,0.005,0.01
2809,energy,noisyFCN,32,1.000000e-03,0.0010,"0:0.21069632132407207,10:0.06689823095932627,2...",180,0.009672,0.01,0.001,0.01
3613,kin8nm,noisyFCN,32,1.000000e-03,0.0001,"0:0.6952972416145836,10:0.27510637251101255,20...",770,0.073846,0.01,0.050,0.01
3717,power-plant,noisyFCN,32,1.000000e-09,0.0005,"0:0.061912036158863724,10:0.05718635360525901,...",250,0.049633,0.01,0.001,0.01
4643,protein-tertiary-structure,noisyFCN,32,1.000000e-03,0.0005,"0:0.6445964563084088,10:0.5433830105470941,20:...",470,0.463667,0.01,0.050,0.01
4453,wine-quality-red,noisyFCN,32,1.000000e-03,0.0005,"0:0.7440498685661485,10:0.5960992919931225,20:...",10,0.596099,0.01,0.001,0.01
4451,yacht,noisyFCN,32,1.000000e-05,0.0010,"0:0.7474827848064656,10:0.15739880489938113,20...",160,0.037691,0.01,0.050,0.01

In [15]:
result_df[(result_df['dataset_name']=='yacht') & (result_df['model_name']=='FCN')]

,dataset_name,model_name,batch_size,weight_decay,learning_rate,epoch2loss,best_epoch,best_loss,fix_noiselevel,init_noiselevel,dropout_prob
4363,yacht,FCN,32,1.000000e-01,0.0001,"0:0.9797534889590984,10:0.7827953518507431,20:...",820,0.104892,0.01,0.01,0.01
4367,yacht,FCN,32,1.000000e-01,0.0005,"0:0.923271701350504,10:0.3916637308110996,20:0...",250,0.106295,0.01,0.01,0.01
4370,yacht,FCN,32,1.000000e-01,0.0010,"0:0.8323878799068684,10:0.24870033118007137,20...",120,0.105505,0.01,0.01,0.01
4371,yacht,FCN,32,1.000000e-01,0.0020,"0:0.6512507468899903,10:0.1742813206813773,20:...",90,0.105757,0.01,0.01,0.01
4465,yacht,FCN,32,1.000000e-02,0.0001,"0:0.99206779753432,10:0.764383804214244,20:0.5...",1990,0.043729,0.01,0.01,0.01
4482,yacht,FCN,32,1.000000e-02,0.0005,"0:0.9026694788689517,10:0.30306571775553176,20...",440,0.042818,0.01,0.01,0.01
4488,yacht,FCN,32,1.000000e-02,0.0010,"0:0.7910901126034406,10:0.1552651389606145,20:...",230,0.041983,0.01,0.01,0.01
4492,yacht,FCN,32,1.000000e-02,0.0020,"0:0.5815842515546448,10:0.08588922594213973,20...",80,0.042492,0.01,0.01,0.01
4522,yacht,FCN,32,1.000000e-03,0.0001,"0:1.0009611701186822,10:0.7621747944792923,20:...",1460,0.046918,0.01,0.01,0.01
4524,yacht,FCN,32,1.000000e-03,0.0005,"0:0.8656817216824513,10:0.284135197436323,20:0...",400,0.041983,0.01,0.01,0.01
4526,yacht,FCN,32,1.000000e-03,0.0010,"0:0.7471171813400425,10:0.15211861834112478,20...",150,0.040630,0.01,0.01,0.01
4527,yacht,FCN,32,1.000000e-03,0.0020,"0:0.5919273065377255,10:0.07605685487389564,20...",40,0.049033,0.01,0.01,0.01
4530,yacht,FCN,32,1.000000e-09,0.0020,"0:0.5539469517785676,10:0.08721987814258556,20...",100,0.049914,0.01,0.01,0.01
4534,yacht,FCN,32,1.000000e-09,0.0010,"0:0.7722123171310036,10:0.17469490902156246,20...",160,0.042398,0.01,0.01,0.01
4535,yacht,FCN,32,1.000000e-09,0.0005,"0:0.8557409485408238,10:0.2876614380965427,20:...",230,0.047639,0.01,0.01,0.01
4544,yacht,FCN,32,1.000000e-09,0.0001,"0:0.9980971285566993,10:0.7659355020279787,20:...",1120,0.047719,0.01,0.01,0.01
4545,yacht,FCN,32,1.000000e-05,0.0020,"0:0.5953164684115624,10:0.08079149617650071,20...",90,0.045057,0.01,0.01,0.01
4546,yacht,FCN,32,1.000000e-05,0.0010,"0:0.7374410840199919,10:0.15934726273891878,20...",120,0.045207,0.01,0.01,0.01
4547,yacht,FCN,32,1.000000e-05,0.0005,"0:0.8790162866602138,10:0.28304822284226516,20...",360,0.047819,0.01,0.01,0.01
4551,yacht,FCN,32,1.000000e-05,0.0001,"0:1.0078539351249227,10:0.757653199609445,20:0...",980,0.052215,0.01,0.01,0.01
4552,yacht,FCN,32,1.000000e-04,0.0020,"0:0.5923495749137839,10:0.07575875860513473,20...",40,0.049069,0.01,0.01,0.01
4554,yacht,FCN,32,1.000000e-04,0.0010,"0:0.7705993964866715,10:0.1784539264732478,20:...",120,0.046754,0.01,0.01,0.01
4555,yacht,FCN,32,1.000000e-04,0.0005,"0:0.8739541286108444,10:0.29644687103616946,20...",320,0.046965,0.01,0.01,0.01
4562,yacht,FCN,32,1.000000e-04,0.0001,"0:0.9760673938284115,10:0.7509658368412329,20:...",1150,0.050715,0.01,0.01,0.01

In [16]:
result_df.columns

Index(['dataset_name', 'model_name', 'batch_size', 'weight_decay',
       'learning_rate', 'epoch2loss', 'best_epoch', 'best_loss',
       'fix_noiselevel', 'init_noiselevel', 'dropout_prob'],
      dtype='object')

In [17]:
unique_settings = result_df[['dataset_name', 'model_name', 'batch_size', 'weight_decay',
       'learning_rate', 'fix_noiselevel', 'init_noiselevel', 'dropout_prob']].drop_duplicates()

In [18]:
unique_settings.to_csv('unique_settings.csv')

In [19]:
result_df.to_csv('settings_loss.csv')

找出还没有跑的settings

In [20]:
dataset_names = ['bostonHousing', 'concrete', 'energy', 'kin8nm', 'power-plant', 'protein-tertiary-structure', 'wine-quality-red', 'yacht']
weight_decays = [0.1, 0.01, 0.001, 0.0001, 1e-05, 1e-09]
learning_rates = [0.0001, 0.0005, 0.001, 0.002]
dropout_probs = [0.2, 0.1, 0.05, 0.01, 0.005, 0.001]
fix_noiselevels = [0.001, 0.005, 0.01, 0.05, 0.1]
init_noiselevels = [0.001, 0.005, 0.01, 0.05, 0.1]

In [21]:
import itertools

In [22]:
FCN_settings = set(itertools.product(dataset_names, weight_decays, learning_rates))
FCN_settings_runned = unique_settings[unique_settings['model_name']=='FCN'][['dataset_name', 'weight_decay', 'learning_rate']].values
FCN_settings_runned = set([tuple(setting) for setting in FCN_settings_runned.tolist()])
print(len(FCN_settings-FCN_settings_runned), FCN_settings-FCN_settings_runned)

0 set()

In [23]:
dropoutFCN_settings = set(itertools.product(dataset_names, weight_decays, learning_rates, dropout_probs))
dropoutFCN_settings_runned = unique_settings[unique_settings['model_name']=='dropoutFCN'][['dataset_name', 'weight_decay', 'learning_rate', 'dropout_prob']].values
dropoutFCN_settings_runned = set([tuple(setting) for setting in dropoutFCN_settings_runned.tolist()])
print(len(dropoutFCN_settings-dropoutFCN_settings_runned), dropoutFCN_settings-dropoutFCN_settings_runned)

0 set()

In [24]:
fixnoiseFCN_settings = set(itertools.product(dataset_names, weight_decays, learning_rates, fix_noiselevels))
fixnoiseFCN_settings_runned = unique_settings[unique_settings['model_name']=='fixnoiseFCN'][['dataset_name', 'weight_decay', 'learning_rate', 'fix_noiselevel']].values
fixnoiseFCN_settings_runned = set([tuple(setting) for setting in fixnoiseFCN_settings_runned.tolist()])
print(len(fixnoiseFCN_settings-fixnoiseFCN_settings_runned), fixnoiseFCN_settings-fixnoiseFCN_settings_runned)

0 set()

In [25]:
fixnoiseFCN_settings-fixnoiseFCN_settings_runned

set()

In [26]:
noisyFCN_settings = set(itertools.product(dataset_names, weight_decays, learning_rates, fix_noiselevels))
noisyFCN_settings_runned = unique_settings[unique_settings['model_name']=='noisyFCN'][['dataset_name', 'weight_decay', 'learning_rate', 'init_noiselevel']].values
noisyFCN_settings_runned = set([tuple(setting) for setting in noisyFCN_settings_runned.tolist()])
print(len(noisyFCN_settings-noisyFCN_settings_runned), noisyFCN_settings-noisyFCN_settings_runned)

96 {('protein-tertiary-structure', 0.01, 0.0001, 0.1), ('wine-quality-red', 1e-09, 0.001, 0.1), ('protein-tertiary-structure', 1e-09, 0.002, 0.005), ('protein-tertiary-structure', 1e-09, 0.001, 0.05), ('yacht', 1e-09, 0.002, 0.1), ('wine-quality-red', 1e-09, 0.0001, 0.01), ('protein-tertiary-structure', 1e-09, 0.0001, 0.001), ('yacht', 0.1, 0.002, 0.001), ('yacht', 0.1, 0.0005, 0.01), ('yacht', 0.1, 0.002, 0.005), ('yacht', 1e-09, 0.0005, 0.05), ('protein-tertiary-structure', 1e-09, 0.0001, 0.1), ('yacht', 0.1, 0.002, 0.1), ('yacht', 1e-09, 0.0001, 0.05), ('yacht', 1e-09, 0.001, 0.001), ('protein-tertiary-structure', 1e-09, 0.002, 0.01), ('wine-quality-red', 0.1, 0.002, 0.1), ('wine-quality-red', 1e-09, 0.002, 0.001), ('yacht', 1e-09, 0.002, 0.001), ('wine-quality-red', 0.1, 0.0005, 0.1), ('yacht', 1e-09, 0.001, 0.1), ('yacht', 1e-09, 0.002, 0.005), ('yacht', 0.1, 0.0001, 0.05), ('wine-quality-red', 1e-09, 0.001, 0.05), ('wine-quality-red', 1e-09, 0.002, 0.1), ('yacht', 0.1, 0.001, 0.001), ('yacht', 1e-09, 0.0001, 0.01), ('yacht', 1e-09, 0.002, 0.05), ('protein-tertiary-structure', 1e-09, 0.0005, 0.001), ('protein-tertiary-structure', 1e-09, 0.002, 0.05), ('yacht', 0.1, 0.001, 0.005), ('wine-quality-red', 1e-09, 0.0005, 0.1), ('protein-tertiary-structure', 1e-09, 0.0005, 0.005), ('yacht', 0.1, 0.001, 0.1), ('protein-tertiary-structure', 1e-09, 0.0001, 0.005), ('protein-tertiary-structure', 1e-09, 0.0005, 0.1), ('wine-quality-red', 0.1, 0.002, 0.001), ('protein-tertiary-structure', 1e-09, 0.0001, 0.05), ('yacht', 0.1, 0.0001, 0.01), ('wine-quality-red', 1e-09, 0.001, 0.01), ('yacht', 0.1, 0.002, 0.05), ('wine-quality-red', 0.1, 0.002, 0.005), ('wine-quality-red', 0.1, 0.0005, 0.001), ('yacht', 1e-09, 0.002, 0.01), ('wine-quality-red', 0.1, 0.0001, 0.001), ('wine-quality-red', 0.1, 0.0005, 0.005), ('yacht', 1e-09, 0.001, 0.005), ('protein-tertiary-structure', 1e-09, 0.001, 0.1), ('yacht', 1e-09, 0.001, 0.05), ('wine-quality-red', 1e-09, 0.002, 0.005), ('wine-quality-red', 0.1, 0.0001, 0.005), ('wine-quality-red', 1e-09, 0.0005, 0.001), ('protein-tertiary-structure', 1e-09, 0.0001, 0.01), ('yacht', 0.1, 0.002, 0.01), ('wine-quality-red', 0.1, 0.0001, 0.1), ('wine-quality-red', 1e-09, 0.002, 0.05), ('wine-quality-red', 1e-09, 0.0001, 0.001), ('wine-quality-red', 1e-09, 0.0005, 0.005), ('yacht', 1e-09, 0.0005, 0.1), ('wine-quality-red', 0.1, 0.002, 0.01), ('wine-quality-red', 1e-09, 0.0001, 0.005), ('yacht', 0.1, 0.0005, 0.001), ('yacht', 0.1, 0.001, 0.05), ('wine-quality-red', 1e-09, 0.0001, 0.1), ('protein-tertiary-structure', 1e-09, 0.0005, 0.05), ('wine-quality-red', 0.1, 0.0005, 0.01), ('yacht', 1e-09, 0.001, 0.01), ('protein-tertiary-structure', 1e-09, 0.001, 0.001), ('wine-quality-red', 1e-09, 0.002, 0.01), ('yacht', 0.1, 0.0005, 0.1), ('protein-tertiary-structure', 1e-09, 0.001, 0.005), ('wine-quality-red', 0.1, 0.002, 0.05), ('yacht', 0.1, 0.0001, 0.1), ('wine-quality-red', 1e-09, 0.0005, 0.01), ('yacht', 0.1, 0.001, 0.01), ('yacht', 1e-09, 0.0005, 0.001), ('wine-quality-red', 0.1, 0.0005, 0.05), ('protein-tertiary-structure', 1e-09, 0.002, 0.1), ('protein-tertiary-structure', 1e-09, 0.0005, 0.01), ('yacht', 1e-09, 0.0001, 0.001), ('wine-quality-red', 0.1, 0.0001, 0.05), ('yacht', 1e-09, 0.0005, 0.005), ('yacht', 1e-09, 0.0001, 0.005), ('wine-quality-red', 1e-09, 0.0005, 0.05), ('yacht', 1e-09, 0.0001, 0.1), ('protein-tertiary-structure', 1e-09, 0.001, 0.01), ('wine-quality-red', 1e-09, 0.0001, 0.05), ('yacht', 0.1, 0.0001, 0.001), ('yacht', 0.1, 0.0005, 0.005), ('wine-quality-red', 1e-09, 0.001, 0.001), ('wine-quality-red', 0.1, 0.0001, 0.01), ('yacht', 0.1, 0.0005, 0.05), ('protein-tertiary-structure', 1e-09, 0.002, 0.001), ('wine-quality-red', 1e-09, 0.001, 0.005), ('yacht', 0.1, 0.0001, 0.005), ('yacht', 1e-09, 0.0005, 0.01)}

In [27]:
noisyFCN_settings-noisyFCN_settings_runned

{('protein-tertiary-structure', 1e-09, 0.0001, 0.001),
 ('protein-tertiary-structure', 1e-09, 0.0001, 0.005),
 ('protein-tertiary-structure', 1e-09, 0.0001, 0.01),
 ('protein-tertiary-structure', 1e-09, 0.0001, 0.05),
 ('protein-tertiary-structure', 1e-09, 0.0001, 0.1),
 ('protein-tertiary-structure', 1e-09, 0.0005, 0.001),
 ('protein-tertiary-structure', 1e-09, 0.0005, 0.005),
 ('protein-tertiary-structure', 1e-09, 0.0005, 0.01),
 ('protein-tertiary-structure', 1e-09, 0.0005, 0.05),
 ('protein-tertiary-structure', 1e-09, 0.0005, 0.1),
 ('protein-tertiary-structure', 1e-09, 0.001, 0.001),
 ('protein-tertiary-structure', 1e-09, 0.001, 0.005),
 ('protein-tertiary-structure', 1e-09, 0.001, 0.01),
 ('protein-tertiary-structure', 1e-09, 0.001, 0.05),
 ('protein-tertiary-structure', 1e-09, 0.001, 0.1),
 ('protein-tertiary-structure', 1e-09, 0.002, 0.001),
 ('protein-tertiary-structure', 1e-09, 0.002, 0.005),
 ('protein-tertiary-structure', 1e-09, 0.002, 0.01),
 ('protein-tertiary-structure', 1e-09, 0.002, 0.05),
 ('protein-tertiary-structure', 1e-09, 0.002, 0.1),
 ('protein-tertiary-structure', 0.01, 0.0001, 0.1),
 ('wine-quality-red', 1e-09, 0.0001, 0.001),
 ('wine-quality-red', 1e-09, 0.0001, 0.005),
 ('wine-quality-red', 1e-09, 0.0001, 0.01),
 ('wine-quality-red', 1e-09, 0.0001, 0.05),
 ('wine-quality-red', 1e-09, 0.0001, 0.1),
 ('wine-quality-red', 1e-09, 0.0005, 0.001),
 ('wine-quality-red', 1e-09, 0.0005, 0.005),
 ('wine-quality-red', 1e-09, 0.0005, 0.01),
 ('wine-quality-red', 1e-09, 0.0005, 0.05),
 ('wine-quality-red', 1e-09, 0.0005, 0.1),
 ('wine-quality-red', 1e-09, 0.001, 0.001),
 ('wine-quality-red', 1e-09, 0.001, 0.005),
 ('wine-quality-red', 1e-09, 0.001, 0.01),
 ('wine-quality-red', 1e-09, 0.001, 0.05),
 ('wine-quality-red', 1e-09, 0.001, 0.1),
 ('wine-quality-red', 1e-09, 0.002, 0.001),
 ('wine-quality-red', 1e-09, 0.002, 0.005),
 ('wine-quality-red', 1e-09, 0.002, 0.01),
 ('wine-quality-red', 1e-09, 0.002, 0.05),
 ('wine-quality-red', 1e-09, 0.002, 0.1),
 ('wine-quality-red', 0.1, 0.0001, 0.001),
 ('wine-quality-red', 0.1, 0.0001, 0.005),
 ('wine-quality-red', 0.1, 0.0001, 0.01),
 ('wine-quality-red', 0.1, 0.0001, 0.05),
 ('wine-quality-red', 0.1, 0.0001, 0.1),
 ('wine-quality-red', 0.1, 0.0005, 0.001),
 ('wine-quality-red', 0.1, 0.0005, 0.005),
 ('wine-quality-red', 0.1, 0.0005, 0.01),
 ('wine-quality-red', 0.1, 0.0005, 0.05),
 ('wine-quality-red', 0.1, 0.0005, 0.1),
 ('wine-quality-red', 0.1, 0.002, 0.001),
 ('wine-quality-red', 0.1, 0.002, 0.005),
 ('wine-quality-red', 0.1, 0.002, 0.01),
 ('wine-quality-red', 0.1, 0.002, 0.05),
 ('wine-quality-red', 0.1, 0.002, 0.1),
 ('yacht', 1e-09, 0.0001, 0.001),
 ('yacht', 1e-09, 0.0001, 0.005),
 ('yacht', 1e-09, 0.0001, 0.01),
 ('yacht', 1e-09, 0.0001, 0.05),
 ('yacht', 1e-09, 0.0001, 0.1),
 ('yacht', 1e-09, 0.0005, 0.001),
 ('yacht', 1e-09, 0.0005, 0.005),
 ('yacht', 1e-09, 0.0005, 0.01),
 ('yacht', 1e-09, 0.0005, 0.05),
 ('yacht', 1e-09, 0.0005, 0.1),
 ('yacht', 1e-09, 0.001, 0.001),
 ('yacht', 1e-09, 0.001, 0.005),
 ('yacht', 1e-09, 0.001, 0.01),
 ('yacht', 1e-09, 0.001, 0.05),
 ('yacht', 1e-09, 0.001, 0.1),
 ('yacht', 1e-09, 0.002, 0.001),
 ('yacht', 1e-09, 0.002, 0.005),
 ('yacht', 1e-09, 0.002, 0.01),
 ('yacht', 1e-09, 0.002, 0.05),
 ('yacht', 1e-09, 0.002, 0.1),
 ('yacht', 0.1, 0.0001, 0.001),
 ('yacht', 0.1, 0.0001, 0.005),
 ('yacht', 0.1, 0.0001, 0.01),
 ('yacht', 0.1, 0.0001, 0.05),
 ('yacht', 0.1, 0.0001, 0.1),
 ('yacht', 0.1, 0.0005, 0.001),
 ('yacht', 0.1, 0.0005, 0.005),
 ('yacht', 0.1, 0.0005, 0.01),
 ('yacht', 0.1, 0.0005, 0.05),
 ('yacht', 0.1, 0.0005, 0.1),
 ('yacht', 0.1, 0.001, 0.001),
 ('yacht', 0.1, 0.001, 0.005),
 ('yacht', 0.1, 0.001, 0.01),
 ('yacht', 0.1, 0.001, 0.05),
 ('yacht', 0.1, 0.001, 0.1),
 ('yacht', 0.1, 0.002, 0.001),
 ('yacht', 0.1, 0.002, 0.005),
 ('yacht', 0.1, 0.002, 0.01),
 ('yacht', 0.1, 0.002, 0.05),
 ('yacht', 0.1, 0.002, 0.1)}

In [31]:
result_df['fix'].unique()

array([0.01 , 0.2  , 0.1  , 0.05 , 0.005, 0.001])